/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class JNITest */

#ifndef _Included_JNITest
#define _Included_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNITest
 * Method:    wait
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_viktorc_pp4j_impl_JNITest_doStuff
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
