/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class JNIWrapper */

#ifndef _Included_JNIWrapper
#define _Included_JNIWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIWrapper
 * Method:    wait
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_viktorc_pp4j_impl_JNIWrapper_doStuff
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
